import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { randomUUID } from "node:crypto";

import makeDebug from "debug";

import QRCode from "qrcode";
import { createError } from "h3";
import { execa } from "execa";

import {
  WG_ALLOWED_IPS,
  WG_DEFAULT_ADDRESS,
  WG_DEFAULT_DNS,
  WG_HOST,
  WG_MTU,
  WG_PATH,
  WG_PERSISTENT_KEEPALIVE,
  WG_PORT,
  WG_POST_DOWN,
  WG_POST_UP,
  WG_PRE_DOWN,
  WG_PRE_UP,
} from "../config";

type Client = {
  id: string;
  name: string;
  enabled: boolean;
  address: string;
  privateKey: string;
  publicKey: string;
  preSharedKey: string;
  createdAt: string;
  updatedAt: string;
  allowedIPs?: string;
};

type Config = {
  server: {
    privateKey: string;
    publicKey: string;
    address: string;
  };
  clients: Record<string, Client>;
};

const debug = makeDebug("WireGuard");

const jsonConfigPath = join(WG_PATH, "wg0.json");
const wgConfigPath = join(WG_PATH, "wg0.conf");

async function exec(cmd: string, { log = true as string | boolean } = {}) {
  if (typeof log === "string") {
    console.log(`$ ${log}`);
  } else if (log === true) {
    console.log(`$ ${cmd}`);
  }

  if (process.platform !== "linux") {
    return "";
  }

  const { stdout } = await execa(cmd, { stdio: "pipe", shell: "bash", timeout: 10_000 });

  return stdout;

  // return new Promise((resolve, reject) => {
  //   childProcess.exec(
  //     cmd,
  //     {
  //       shell: "bash",
  //     },
  //     (err, stdout) => {
  //       if (err) {
  //         reject(err);
  //         return;
  //       }
  //       resolve(String(stdout).trim());
  //     },
  //   );
  // });
}

function isValidIPv4(str: string) {
  const blocks = str.split(".");
  if (blocks.length !== 4) return false;

  for (const value of blocks) {
    const number = Number.parseInt(value, 10);
    if (Number.isNaN(number)) return false;
    if (number < 0 || number > 255) return false;
  }

  return true;
}

function __saveConfig(config: Config) {
  let result = `
# Note: Do not edit this file directly.
# Your changes will be overwritten!

# Server
[Interface]
PrivateKey = ${config.server.privateKey}
Address = ${config.server.address}/24
ListenPort = 51820
PreUp = ${WG_PRE_UP}
PostUp = ${WG_POST_UP}
PreDown = ${WG_PRE_DOWN}
PostDown = ${WG_POST_DOWN}
`;

  for (const [clientId, client] of Object.entries(config.clients)) {
    if (!client.enabled) continue;

    result += `

# Client: ${client.name} (${clientId})
[Peer]
PublicKey = ${client.publicKey}
${client.preSharedKey ? `PresharedKey = ${client.preSharedKey}\n` : ""}AllowedIPs = ${client.address}/32`;
  }

  debug("Config saving...");

  if (!existsSync(WG_PATH)) mkdirSync(WG_PATH);

  writeFileSync(jsonConfigPath, JSON.stringify(config, undefined, 2));
  writeFileSync(wgConfigPath, result);
  debug("Config saved.");
}

async function __syncConfig() {
  debug("Config syncing...");
  await exec("wg syncconf wg0 <(wg-quick strip wg0)");
  debug("Config synced.");
}

async function getConfig() {
  debug("Loading configuration...");

  let config: Config;

  if (existsSync(jsonConfigPath)) {
    try {
      config = JSON.parse(readFileSync(jsonConfigPath, "utf8"));
      debug("Configuration loaded.");
    } catch {
      throw new Error("Invalid configuration file.");
    }
  } else {
    const privateKey = await exec("wg genkey");

    config = {
      server: {
        privateKey,
        publicKey: await exec(`echo ${privateKey} | wg pubkey`, {
          log: "echo ***hidden*** | wg pubkey",
        }),
        address: WG_DEFAULT_ADDRESS.replace("x", "1"),
      },
      clients: {},
    };
    debug("Configuration generated.");
  }

  __saveConfig(config);
  await exec("wg-quick down wg0").catch(() => {});
  await exec("wg-quick up wg0").catch((error) => {
    if (error?.message?.includes('Cannot find device "wg0"')) {
      throw new Error(
        'WireGuard exited with the error: Cannot find device "wg0"\nThis usually means that your host\'s kernel does not support WireGuard!',
      );
    }

    throw error;
  });

  // await exec(`iptables -t nat -A POSTROUTING -s ${WG_DEFAULT_ADDRESS.replace('x', '0')}/24 -o ' + WG_DEVICE + ' -j MASQUERADE`);
  // await exec('iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT');
  // await exec('iptables -A FORWARD -i wg0 -j ACCEPT');
  // await exec('iptables -A FORWARD -o wg0 -j ACCEPT');
  await __syncConfig();

  return config;
}

const config = await getConfig();

async function saveConfig() {
  __saveConfig(config);
  await __syncConfig();
}

async function getClients() {
  const clients = Object.entries(config.clients).map(([clientId, client]) => ({
    id: clientId,
    name: client.name,
    enabled: client.enabled,
    address: client.address,
    publicKey: client.publicKey,
    createdAt: new Date(client.createdAt).toString(),
    updatedAt: new Date(client.updatedAt).toString(),
    allowedIPs: client.allowedIPs,
    downloadableConfig: "privateKey" in client,
    persistentKeepalive: undefined as string | undefined,
    latestHandshakeAt: undefined as string | undefined,
    transferRx: undefined as number | undefined,
    transferTx: undefined as number | undefined,
  }));

  // Loop WireGuard status
  const dump = await exec("wg show wg0 dump", {
    log: false,
  });
  for (const line of dump.trim().split("\n").slice(1)) {
    const [publicKey, preSharedKey, endpoint, allowedIps, latestHandshakeAt, transferRx, transferTx, persistentKeepalive] =
      line.split("\t");

    const client = clients.find((client) => client.publicKey === publicKey);
    if (!client) continue;

    client.latestHandshakeAt = latestHandshakeAt === "0" ? undefined : new Date(Number(`${latestHandshakeAt}000`)).toString();
    client.transferRx = Number(transferRx);
    client.transferTx = Number(transferTx);
    client.persistentKeepalive = persistentKeepalive;
  }

  return clients;
}

function getClient(clientId: string) {
  const client = config.clients[clientId];
  if (!client) {
    throw createError({
      status: 404,
      message: `Client Not Found: ${clientId}`,
    });
  }

  return client;
}

function getClientConfiguration(clientId: string) {
  const client = getClient(clientId);

  return `
[Interface]
PrivateKey = ${client.privateKey ? `${client.privateKey}` : "REPLACE_ME"}
Address = ${config.server.address}/24
${WG_DEFAULT_DNS ? `DNS = ${WG_DEFAULT_DNS}\n` : ""}\
${WG_MTU ? `MTU = ${WG_MTU}\n` : ""}\

[Peer]
PublicKey = ${config.server.publicKey}
${client.preSharedKey ? `PresharedKey = ${client.preSharedKey}\n` : ""}AllowedIPs = ${WG_ALLOWED_IPS}
PersistentKeepalive = ${WG_PERSISTENT_KEEPALIVE}
Endpoint = ${WG_HOST}:${WG_PORT}`;
}

async function getClientQRCodeSVG(clientId: string) {
  const config = getClientConfiguration(clientId);
  return QRCode.toString(config, {
    type: "svg",
    width: 512,
  });
}

async function createClient(name: string) {
  if (!name) {
    throw new Error("Missing: Name");
  }

  const privateKey = await exec("wg genkey");
  const publicKey = await exec(`echo ${privateKey} | wg pubkey`);
  const preSharedKey = await exec("wg genpsk");

  // find next IP
  let address;
  for (let i = 2; i < 255; i++) {
    const client = Object.values(config.clients).find((client) => {
      return client.address === WG_DEFAULT_ADDRESS.replace("x", String(i));
    });

    if (!client) {
      address = WG_DEFAULT_ADDRESS.replace("x", String(i));
      break;
    }
  }

  if (!address) {
    throw new Error("Maximum number of clients reached.");
  }

  // Create Client
  const id = randomUUID();
  const client = {
    id,
    name,
    address,
    privateKey,
    publicKey,
    preSharedKey,

    createdAt: new Date().toString(),
    updatedAt: new Date().toString(),

    enabled: true,
  };

  config.clients[id] = client;

  await saveConfig();

  return client;
}

async function deleteClient(clientId: string) {
  if (config.clients[clientId]) {
    delete config.clients[clientId];
    await saveConfig();
  }
}

async function enableClient(clientId: string) {
  const client = getClient(clientId);

  client.enabled = true;
  client.updatedAt = new Date().toString();

  await saveConfig();
}

async function disableClient(clientId: string) {
  const client = getClient(clientId);

  client.enabled = false;
  client.updatedAt = new Date().toString();

  await saveConfig();
}

async function updateClientName(clientId: string, name: string) {
  const client = getClient(clientId);

  client.name = name;
  client.updatedAt = new Date().toString();

  await saveConfig();
}

async function updateClientAddress(clientId: string, address: string) {
  const client = getClient(clientId);

  if (!isValidIPv4(address)) {
    throw createError({
      status: 400,
      message: `Invalid Address: ${address}`,
    });
  }

  client.address = address;
  client.updatedAt = new Date().toString();

  await saveConfig();
}

// Shutdown wireguard
async function Shutdown() {
  await exec("wg-quick down wg0").catch(() => {});
}

export default {
  getClients,
  getClient,
  getClientConfiguration,
  getClientQRCodeSVG,
  createClient,
  deleteClient,
  enableClient,
  disableClient,
  updateClientName,
  updateClientAddress,
  Shutdown,
};
